### ISSUE TITLE
Add Italicize, Bold, Underline

### ISSUE THREAD

**Issue by rudrathedev** [AmrDeveloper/CodeView#10]
Would like to see these in editor !

**Comment by AmrDeveloper** [comment]
Hello @rudrathedev,
Thanks for your suggestion, but can you please provide some extra information for example

If you want bold in all keywords in the editor you can make this easily like any other TextView

From XML
```XML
   android:textStyle="bold"
```
or from Java
```java
codeView.setTypeface(textView.getTypeface(), Typeface.BOLD);
```

Or you mean for example to add style for a specific pattern like language keywords

Thanks
Amr Hesham

**Comment by rudrathedev** [comment]
I want it to be for a specific pattern

**Comment by MahmoudMabrok** [comment]
@rudrathedev 
i think it can be added as overflow menu when user select text in code (not sure if it already appear or not).


Could u share a the business case for having bold some text based on pattern.
