### ISSUE TITLE
Event (ex: for pairs)

### ISSUE THREAD

**Issue by Se-Lyan** [AmrDeveloper/CodeView#13]

**Comment by AmrDeveloper** [comment]
Hello @Se-Lyan, 

Thanks for your issue but please provide more details if it is a feature request or issue report and some examples will be very helpful

**Comment by Se-Lyan** [comment]
Event for pair, for ex when pair is added, it would allow me to go back one character to be in the middle of the pair

**Comment by AmrDeveloper** [comment]
Hello @Se-Lyan, 

This feature is available from release `1.3.4` I hope you enjoyed it :D
