### ISSUE TITLE
Custom menu for CodeView

### ISSUE THREAD

**Issue by ansh2166** [AmrDeveloper/CodeView#14]
I want to add custom text selection menu with custom items to my codeview

Like :

![image](https://user-images.githubusercontent.com/72782632/154808131-17cb3f01-40dd-4d47-af85-56888f6136aa.png)

**Comment by AmrDeveloper** [comment]
Hello @ansh2166

Add Custom or Normal Context Menu is the same with CodeView or any EditText,
all you need is to know how to use it with EditText for example and use the same code with CodeView and it will work fine :D

Thanks
