### ISSUE TITLE
Suggestions dont work

### ISSUE THREAD

**Issue by ansh2166** [AmrDeveloper/CodeView#15]
my code doesnt work

public static String[] suggestions = {"!DOCTYPE", "a", "acronym", "abbr", "address"};

ArrayAdapter<String> adapter = new ArrayAdapter<>(this, R.layout.code_suggestions, R.id.suggestItemTextView, suggestions);
cd.setAdapter(adapter);

suggestions dont even appear

**Comment by AmrDeveloper** [comment]
Hello @ansh2166,

Thank you for your issue, from your code example I see that you used the same layout XML from the example app, so I tested your code with it

![auto-complete2](https://user-images.githubusercontent.com/23631699/155696004-11d873f6-d04c-4fd7-84b6-e42987584b01.PNG)


![auto-complete1](https://user-images.githubusercontent.com/23631699/155695998-49c59676-1e7c-40e3-a05c-29d19be155c6.PNG)

And if you want the autocomplete to work with 1 first char you can add ` codeView.setThreshold(1);` and the result will be like this

![auto-complete3](https://user-images.githubusercontent.com/23631699/155699071-6c2cc1f6-c34b-44e7-bde9-6687ea0f8b56.PNG)

Please change the example app and if you will have the same problem you can share more code so we can find the problem together 👍🏻

**Comment by ansh2166** [comment]
I got it to work, last issue, Suggestions are overlapped by keyboard if line is at bottom :(

**Comment by AmrDeveloper** [comment]
Thanks, @ansh2166, i will solve it soon in the next release 😃

**Comment by AmrDeveloper** [comment]
Hello, @ansh2166 I have released version 1.3.3 with solution for your last issue and I will add some extra improvement and options soon, enjoy CodeView 👍🏻
