### ISSUE TITLE
Bring cursor at middle of pair auto complete characters

### ISSUE THREAD

**Issue by m-anshuman2166** [AmrDeveloper/CodeView#18]
Just a simple request/suggestion
for now, in pair auto complete, cursor is moved to right of characters, I would like to see cursor to be put at middle of characters

**Comment by AmrDeveloper** [comment]
Hello @m-anshuman2166 Thanks for your suggestion, we can add this features as a option

Nice Idea

**Comment by AmrDeveloper** [comment]
This feature is ready to use now in version `1.3.4` enjoy and thanks for your suggestions
