### ISSUE TITLE
Cannot remove line number and make it can't be edited 

### ISSUE THREAD

**Issue by SasmitaNovitasari** [AmrDeveloper/CodeView#20]
I try to create something look like this

![Screenshot_20220324-183054_Chrome](https://user-images.githubusercontent.com/50041639/159919164-cf9df643-6f66-4c70-82d0-e85d23f5d911.jpg)

How to remove line number, make it can't be edited and can slide left-right?

**Comment by AmrDeveloper** [comment]
Hello @SasmitaNovitasari,

let me split your questions

> How to remove line number?
By default line number feature is disable and you can enable or disable it using `setEnableLineNumber` method.

> How to disable editing?
After you insert the code you can use `setFocusable(false)`.

> Can you slide left-right?
Yes you can if you have a long line you can scroll it for example

![codeview_long_line](https://user-images.githubusercontent.com/23631699/159924579-4ffc726b-88d2-427c-b8bf-6305c7cc3e49.gif)

If you have any question, feel free to ask it 👍🏻

**Comment by SasmitaNovitasari** [comment]
Now I have new problem. I can't find any documentation like what I need, how to put String code in code view. Like setText or something

Sorry if i ask useless question
