### ISSUE TITLE
Isn't working properly!

### ISSUE THREAD

**Issue by SunPodder** [AmrDeveloper/CodeView#21]
I have added the following code in layout from the docs
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity" >

    <com.amrdeveloper.codeview.CodeView
        android:id="@+id/codeView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/darkGrey"
        android:dropDownHorizontalOffset="0dp"
        android:dropDownSelector="@color/darkGrey"
        android:dropDownWidth="150dp"
	android:gravity="top|start" />

</LinearLayout>
```

The app looks like this
![Screenshot_20220325-153948_Code Editor](https://user-images.githubusercontent.com/73415680/160095945-da653ffa-4753-490a-987f-a66c8b4062e9.jpg)

Keyboard doesn't appear, no response from the app. Why is that?

**Comment by AmrDeveloper** [comment]
Hello @SunPodder,

Can you please share some more information so we can find the problem easily for example

Android Version: ??
CodeView Version: ??

Try to run the example app from this repository and it will be great if you shared your config code

**Comment by m-anshuman2166** [comment]
If text is empty, you must click at center of codeview to show cursor

perhaps it would be better if you `pre`- `specify` code

**Comment by m-anshuman2166** [comment]
Was your issue fixed ?

**Comment by SunPodder** [comment]
Uhh yeah

**Comment by SunPodder** [comment]
I know this is not a bug of the library but i need assistance.
Back then I only tried the demo app and didn't fix my problem. Now I am again working on this project.

This time everything else is fine but the keyboard is not showing up.

I have tried `focusable="true"` in CodeView widget and also tried to open the keyboard manually. Nothing worked.

I am using codes from the demo app. Though I have not applied all the code from it

**Comment by SunPodder** [comment]
Fixed that after using `AppCompatActivity` instead of `android.app.Activity` resulting in 3MB increased apk size. Total 8MB for just writing Hello World in a app. Can't it be decreased?
Also when just using the library it wss 5MB. Most of the phones are now run on API 21 and higher. So can you switch from `AppCompatMultiAutoCompleteTextView` to `MultiAutoCompleteTextView`?
