### ISSUE TITLE
Bug in RTL Languages

### ISSUE THREAD

**Issue by Arashvscode** [AmrDeveloper/CodeView#24]
Hello, in Persian, the editor disappears strangely

**Comment by AmrDeveloper** [comment]
Hello @Arashvscode, 

Thanks for your report, can you share some text example so we can test it and find the issue, 
it will be better if you can share video or gif for the issue if you can 

Thanks
Amr Hesham

**Comment by Arashvscode** [comment]
> Hello @Arashvscode,
> 
> Thanks for your report, can you share some text example so we can test it and find the issue, it will be better if you can share video or gif for the issue if you can
> 
> Thanks Amr Hesham


https://user-images.githubusercontent.com/101287880/164944362-70286960-a9fb-4d65-ba84-b5152d0105a7.mp4

See in video my bro and fixed bug lol

**Comment by AmrDeveloper** [comment]
@Arashvscode Hello, thanks for the report

the editor moves from LTR to RTL when you type LTR language like Arabic or Persian, I will check it and support them

Thanks
Amr Hesham

**Comment by Arashvscode** [comment]
> 

Tnks❤

**Comment by AmrDeveloper** [comment]
> > 
> 
> Tnks❤

@Arashvscode this attribute can solve your problem and make it easy to mix RLT & LRT languages

```XML
android:textDirection="firstStrong"
```

![mix ar](https://user-images.githubusercontent.com/23631699/164981473-d3a7e08b-d4e5-4cb3-9e26-45bddc4f4f01.PNG)

**Comment by Arashvscode** [comment]
It gives me a compilation error. Can you update the library and I get the files?

**Comment by AmrDeveloper** [comment]
@Arashvscode Please check the example app code here

https://github.com/AmrDeveloper/CodeView/blob/9f8efa6d6011e40009bb09417518792ba3d26dc4/app/src/main/res/layout/activity_main.xml#L18

It is successfully built and work without any errors
