### ISSUE TITLE
The autocomplete and The keyboard

### ISSUE THREAD

**Issue by danicaStarR** [AmrDeveloper/CodeView#28]
1.The autocomplete box is in the wrong position
2.The keyboard blocks the input box

https://user-images.githubusercontent.com/103302052/166631466-4a09586d-2e0a-437e-8a43-2ad2aa8ee682.mp4

![](https://user-images.githubusercontent.com/103302052/166631511-b552ff11-c4ec-4bd7-abe0-75d7db4c5155.png)

![](https://user-images.githubusercontent.com/103302052/166631522-3f6825a5-884e-40f5-a46a-83ba3c29d079.png)

### **android version:6.0.1**

# Codes:
MainActivity.java

`
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
		
		
        
        // Your language keywords
        String[] languageKeywords = {"hello","world"};
    // List item custom layout 
         
    // TextView id on your custom layout to put suggestion on it
        CodeView codeView = findViewById(R.id.codeView);
        
        codeView.setEnableLineNumber(true);
        codeView.setLineNumberTextColor(Color.GRAY);
        codeView.enablePairComplete(true);
        codeView.enablePairCompleteCenterCursor(true);
        Map<Character, Character> pairCompleteMap = new HashMap<>();
        pairCompleteMap.put('{', '}');
        pairCompleteMap.put('[', ']');
        pairCompleteMap.put('(', ')');
        pairCompleteMap.put('<', '>');
        pairCompleteMap.put('"', '"');
        codeView.setPairCompleteMap(pairCompleteMap);
        codeView.addSyntaxPattern(Pattern.compile("[0-9]+") , Color.RED);
        codeView.setLineNumberTextSize(15);
        
        
        
    // Create ArrayAdapter object that contain all information
        ArrayAdapter<String> adapter = new ArrayAdapter<>(this, R.layout.list,R.id.v_m_c, languageKeywords);
    // Set the adapter on CodeView object
        codeView.setAdapter(adapter);
        
        Snackbar.make(codeView,"By Ds",Snackbar.LENGTH_SHORT).show();
    }
    
`

## activity_main.xml
`
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	android:layout_width="match_parent"
	android:layout_height="match_parent">

	
        
        <com.amrdeveloper.codeview.CodeView
            android:id="@+id/codeView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/colo"
            android:dropDownWidth="150dp"
            android:dropDownHorizontalOffset="0dp"
            android:dropDownSelector="@color/colo"
            android:gravity="top|start" />
        
	

</androidx.coordinatorlayout.widget.CoordinatorLayout>

`

**Comment by AmrDeveloper** [comment]
Hello @danicaStarR,

Thanks for your report and information, I will test it on old versions and find the problem,

Thanks
Amr Hesham

**Comment by danicaStarR** [comment]
oh,Thank u.😝

**Comment by AmrDeveloper** [comment]
The problem is from vertical offset calculation, i will modify it and test it first with many devices and versions before release it

Thanks bro
Amr Hesham

**Comment by m-anshuman2166** [comment]
Well kinda same issue in my case too

**Comment by AmrDeveloper** [comment]
Hello guys @danicaStarR @m-anshuman2166, 

I have fixed the problem in Android 6 and below and tested it with different versions, please try to test the example app too on many different devices so we can make sure it is good and fix the problem before we release 1.3.5, I will keep testing 👍🏻 

Thanks
Amr Hesham

**Comment by danicaStarR** [comment]
OK 😆

**Comment by m-anshuman2166** [comment]
![image](https://user-images.githubusercontent.com/72782632/168002575-b356d482-9097-4b96-93f1-58db793ff3a3.png)
Looks better !

**Comment by m-anshuman2166** [comment]
@danicaStarR is your issue solved ?

**Comment by danicaStarR** [comment]
@m-anshuman2166 I've been busy lately and haven't tried the new version

**Comment by AmrDeveloper** [comment]
This issue is solved in the last version
