### ISSUE TITLE
Add line numbers

### ISSUE THREAD

**Issue by rosstonovsky** [AmrDeveloper/CodeView#4]
I would like to see line numbers.

**Comment by AmrDeveloper** [comment]
Hello, @rosstonovsky Thanks for your suggestion, I already have created an optional line number and snippets support for the next version `1.1.0` and it will be released today, this is a small demo

![codeview_snippet_gif](https://user-images.githubusercontent.com/23631699/142605460-0bb341e4-97c5-495c-ae65-7dccdeca2ffa.gif)

I hope you will enjoy this version
