### ISSUE TITLE
CodeViewAdapter.updateCodes() is not available

### ISSUE THREAD

**Issue by rundone** [AmrDeveloper/CodeView#43]
If CodeViewAdapter.updateCodes() is called, auto complete cannot be used and the drop-down box will not be displayed

**Comment by AmrDeveloper** [comment]
Hello @rundone,

Thank you for reporting, i will check it

Thank you,
Amr Hesham

**Comment by rundone** [comment]
I don't know if it's because I'm using it in a fragment, plus I've found that LineNumber doesn't work either

**Comment by AmrDeveloper** [comment]
> I don't know if it's because I'm using it in a fragment, plus I've found that LineNumber doesn't work either

Can you share more info about LineNumber problem so we can solve them

**Comment by rundone** [comment]
https://github.com/AmrDeveloper/CodeView/assets/155033180/8a0d71ab-09bb-4909-b839-23249fd78d2f

In the video, you can see that the line number is not displayed

**Comment by rundone** [comment]
https://github.com/AmrDeveloper/CodeView/assets/155033180/04a515d7-d558-47f4-a16f-8a7ecb253702

In the video, you can see that the line number is not displayed

**Comment by AmrDeveloper** [comment]
@rundone Thank you for sharing video, i tested line number with fragment it's work but default text size is small can you please try

```java
codeView.setLineNumberTextSize(25f);
```

**Comment by AmrDeveloper** [comment]
@rundone Auto Complete issue is fixed at this commit https://github.com/AmrDeveloper/CodeView/commit/2a04be57bd9f0006c23a7cfbd66d9f869825bd57, once you confirm LineNumber i can release new version to use

**Comment by AmrDeveloper** [comment]
I released '1.3.9' for updateCodes fix
