### ISSUE TITLE
Pre specify code

### ISSUE THREAD

**Issue by rudrathedev** [AmrDeveloper/CodeView#6]
I want to set code of code view from code

**Comment by AmrDeveloper** [comment]
Hello @rudrathedev,

If you want to insert a code programmatically into CodeView you should use `setTextHighlighted` method, for example

```java
codeView.setTextHighlighted("public class Main { }");
```

**Comment by rudrathedev** [comment]
What will be color of code after i apply `setTextHighlighted`

**Comment by rudrathedev** [comment]
Also my text is multi - line, 

my String for now 
`String htmlcode = "<!DOCTYPE html> /n <html> /n <title>Wiggle Editor</title> /n <body> /n /n <h1>This is a large text</h1> /n <p>This is a paragraph.</p> /n /n </body> /n </html>";`

**Comment by AmrDeveloper** [comment]
> What will be color of code after i apply `setTextHighlighted`

The color of the code will depend only on your set of patterns not by how the text is inserted by the user or programmatically

**Comment by AmrDeveloper** [comment]
> Also my text is multi - line,
> 
> my String for now `String htmlcode = "<!DOCTYPE html> /n <html> /n <title>Wiggle Editor</title> /n <body> /n /n <h1>This is a large text</h1> /n <p>This is a paragraph.</p> /n /n </body> /n </html>";`

There is no problem if your text is a single or multi-lines just add `\n` not `/n` when you want to go to the next line

And insert it one like

```java
codeView.setTextHighlighted(htmlcode);
```

**Comment by rudrathedev** [comment]
Thats so nice !

Am using this lib in my project :)
