### ISSUE TITLE
Undo and Redo

### ISSUE THREAD

**Issue by rudrathedev** [AmrDeveloper/CodeView#7]
Please add undo and Redo features

**Comment by AmrDeveloper** [comment]
Hello @rudrathedev Thanks for your suggestion, I will put it on the TODO list 😄 

Enjoy CodeView

**Comment by rudrathedev** [comment]
I got a workaround, leave it to me, I'll create a pr for this

**Comment by AmrDeveloper** [comment]
Hello @rudrathedev,

If you mean by workaround is to implement this feature outside the CodeView class you can add this code in the example app with documentation.

I am thinking that to support this nice feature inside the Codeview, we need to make it as customizable commands, maybe create a solution inspired from Command or Memento design pattern, also we need to decide if we will support those commands for each char or word, we need also to think about Command interface design and how to make it easy to create a new custom command.

We need to search how popular code editors implemented this feature

**Comment by rudrathedev** [comment]
#8 will be able to solve this
