### ISSUE TITLE
"Auto Indentation" is not the right implementation

### ISSUE THREAD

**Issue by yiszza** [AmrDeveloper/CodeView#9]
It should look like this:
```
{
    {
        {
        }
    }
}
```

but in fact it looks like this:
```
{
    {
        {
            }
        }
    }

```

**Comment by AmrDeveloper** [comment]
Hello @yiszza, thanks for submitting this issue

I will work to improve this feature and provide some examples with space and other char then { }

Thanks
Amr Hesham

**Comment by AmrDeveloper** [comment]
Hello @yiszza, Please check the new version (1.3.0) it has a lot of improvement in Auto indenting and other new features 😃 

![1-3-0-multi-indenting-demo](https://user-images.githubusercontent.com/23631699/151380932-8fb69e4f-903f-4045-9aa2-1a2adab06c6f.gif)

Enjoy it
